//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancion
    {
        public int IdCancion { get; set; }
        public int IdAlbum { get; set; }
        public string Titulo { get; set; }
        public decimal Duracion { get; set; }
        public string Plataforma { get; set; }
    
        public virtual Album Album { get; set; }
    }
}
